config/routes.rb
Sample4::Application.routes.draw do
  get "password_resets/new"
  resources :users do 
    member do
      get :following, :followers, :toggle_followmail, :confirm
      post :activate
    end
  end
  resources :password_resets
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/inbox',   to: 'static_pages#inbox',   via: 'get'
  match '/outbox',  to: 'static_pages#outbox',  via: 'get'
  

  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end

  def edit
    @user = User.find_by_remember_token!(params[:id])
  end

  def update
    @user = User.find_by_remember_token!(params[:id])
    if @user.remember_token_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(user_params)
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>
<h1>Reset your password</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
      <% if @user.errors.any? %>
     <div class="error_messages">
       <h2>Form is invalid</h2>
       <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Update Password", class: "btn btn-large btn-primary" %></div>
  </div>
</div>
<% end %>

app/views/password_resets/new.html.erb
<% provide(:title, "Reset password") %>
<h1>Reset your password</h1>
<div class="row">
 <div class="span6 offset3">
   <%= form_tag password_resets_path, :method => :post do %>
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
    <%= submit_tag "Reset Password", class: "btn btn-large btn-primary" %>
  </div>
 </div>
<% end %>