config/routes.rb
Sample4::Application.routes.draw do
  get "password_resets/new"
  resources :users do 
    member do
      get :following, :followers, :toggle_followmail, :confirm
      post :activate
    end
  end
  resources :password_resets
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/inbox',   to: 'static_pages#inbox',   via: 'get'
  match '/outbox',  to: 'static_pages#outbox',  via: 'get'
  

  

end

app/views/shared/_delete_link.html.erb
<% if current_user?(object.user) %>
    <%= link_to "delete", object, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: object.content %>
  <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
  <%= form_tag request.fullpath, :method => 'get' do %>
  <div class="row">
    <div class="span6" >
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil,  class: "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= recipient =  User.find_by(id: feed_item.message_to)
  #show recipient's gravatar for sent messages
  if sentMessage?(feed_item)
    link_to gravatar_for(recipient), recipient
  else	
    link_to gravatar_for(feed_item.user), feed_item.user 
  end %>
  <span class="user">
    <% if sentMessage?(feed_item) %>
    <span> To: </span>
    <%= link_to recipient.name, recipient  %>
    <span class="content"><%= feed_item.content.sub(/\*\S*\s/) { "" } %></span>
    <!-- check if it's a received message --> 
    <% elsif feed_item.message_to %>
    <span> From: </span>
    <%= link_to feed_item.user.name, feed_item.user %>
    <span class="content"><%= feed_item.content.sub(/\*\S*\s/) { "" } %></span>
    <% else %> 
    <%= link_to feed_item.user.name, feed_item.user %>
    <span class="content"><%= feed_item.content %></span>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <%= render 'shared/delete_link', object: feed_item %> 
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  <span class="countdown"></span> 
  <span class="btn-group">
    <a class="btn dropdown-toggle" id="replyto" data-toggle="dropdown" href="#">
    Reply To
    <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" >
        <% @user.followed_users.each do |followed| %>
          <li class="recipient" > 
            <% @name = followed.name.gsub(" ", "_") %>
          	<%= link_to @name, "#", :class => "reply" %> 
          </li>
        <% end %>
    </ul>
    
</span>
<span class="btn-group">
<a class="btn dropdown-toggle" id="messageto" data-toggle="dropdown" href="#">
    Message To
    <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" >
        <% @user.followed_users.each do |followed| %>
          <li class="recipient" > 
            <% @name = followed.name.gsub(" ", "_") %>
            <%= link_to @name, "#", :class => "message" %> 
          </li>
        <% end %>
    </ul>
    </span>
<% end %>


app/views/shared/_signed_in.html.erb
<div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

app/views/shared/_signed_out.html.erb
<div class="center hero-unit">
    <h1>Welcome to Rails Social</h1>

    <h2>
      This is a place to meet other rails enthusiasts who love trains and steam engines
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
    <%= link_to "Forgot your password?", new_password_reset_path %> 
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>